from __future__ import annotations

import numpy as np
from numpy.typing import NDArray


def one_qubit_diagonal_group() -> NDArray[np.float64]:
    """Generate the 1-qubit real diagonal Clifford group.

    The group is generated by taking powers of the phase gate P = diag(1, i)
    and retaining those whose diagonal entries are all real (±1).
    This yields 2 group elements.

    Returns:
        Array of shape (2, 2) where each row is a diagonal group element.
    """
    P_diag = np.array([1, complex(0, 1)], dtype=complex)

    diagonal_group = []
    for i in range(1, 5):
        P_power_diag = P_diag ** i
        if np.allclose(P_power_diag.imag, 0):
            diagonal_group.append(P_power_diag.real)

    return np.array(diagonal_group)


def two_qubit_diagonal_group() -> NDArray[np.float64]:
    """Generate the 2-qubit real diagonal Clifford group.

    The group is generated by products of P gates on each qubit and the CZ gate,
    retaining elements whose diagonal entries are all real. This yields 32 elements.

    Returns:
        Array of shape (32, 4) where each row is a diagonal group element.
    """
    P_diag = np.array([1, complex(0, 1)], dtype=complex)
    I_diag = np.array([1, 1], dtype=complex)
    CZ_diag = np.array([1, 1, 1, -1], dtype=complex)

    P1_diag = np.kron(P_diag, I_diag)
    P2_diag = np.kron(I_diag, P_diag)
    P1P2_diag = np.kron(P_diag, P_diag)

    diagonal_group = []
    for i in range(1, 5):
        for j in range(1, 5):
            for k in range(1, 5):
                for l in range(1, 3):
                    result_diag = (P1_diag ** i) * (P2_diag ** j) * (P1P2_diag ** k) * (CZ_diag ** l)
                    if np.allclose(result_diag.imag, 0):
                        diagonal_group.append(result_diag.real)

    return np.array(diagonal_group)


def create_cz_diagonal(qubit1: int, qubit2: int, n_qubits: int) -> NDArray[np.complex128]:
    """Create the diagonal of a CZ gate acting on two qubits in an n-qubit system.

    The CZ gate applies a -1 phase to basis states where both target qubits are |1>.
    Qubit indices use 1-based numbering, with qubit 1 corresponding to the
    most-significant bit in the computational basis ordering.

    Args:
        qubit1: Index of the first qubit (1-based).
        qubit2: Index of the second qubit (1-based).
        n_qubits: Total number of qubits in the system.

    Returns:
        Array of length 2^n_qubits with ±1 complex entries representing the
        diagonal of the CZ gate.
    """
    dim = 2 ** n_qubits
    diagonal = np.ones(dim, dtype=complex)

    for i in range(dim):
        if ((i >> (n_qubits - qubit1)) & 1) and ((i >> (n_qubits - qubit2)) & 1):
            diagonal[i] = -1

    return diagonal


def create_pauli_z_diagonal(qubit: int, n_qubits: int) -> NDArray[np.complex128]:
    """Create the diagonal of a phase gate P on a single qubit in an n-qubit system.

    The phase gate P = diag(1, i) acts on the specified qubit and identity on
    all others, constructed via tensor products.

    Args:
        qubit: Index of the qubit to apply the P gate to (1-based).
        n_qubits: Total number of qubits in the system.

    Returns:
        Array of length 2^n_qubits with complex entries representing the diagonal
        of the n-qubit operator I ⊗ ... ⊗ P ⊗ ... ⊗ I.
    """
    P_single = np.array([1, complex(0, 1)], dtype=complex)
    I_single = np.array([1, 1], dtype=complex)

    result = np.array([1], dtype=complex)
    for q in range(1, n_qubits + 1):
        result = np.kron(result, P_single if q == qubit else I_single)

    return result


def three_qubit_diagonal_group() -> NDArray[np.float64]:
    """Generate the 3-qubit real diagonal Clifford group.

    Generated by products of P gates on each qubit and CZ gates on all 3 pairs,
    retaining elements with real diagonals. This yields 64 elements.

    Returns:
        Array of shape (64, 8) where each row is a diagonal group element.
    """
    n_qubits = 3

    P_gates = [create_pauli_z_diagonal(qubit, n_qubits) for qubit in range(1, n_qubits + 1)]

    CZ12_diag = create_cz_diagonal(1, 2, n_qubits)
    CZ23_diag = create_cz_diagonal(2, 3, n_qubits)
    CZ13_diag = create_cz_diagonal(1, 3, n_qubits)

    diagonal_group = []
    for i in range(1, 5):
        for j in range(1, 5):
            for k in range(1, 5):
                for l in range(1, 3):
                    for m in range(1, 3):
                        for n in range(1, 3):
                            result_diag = (
                                (P_gates[0] ** i)
                                * (P_gates[1] ** j)
                                * (P_gates[2] ** k)
                                * (CZ12_diag ** l)
                                * (CZ23_diag ** n)
                                * (CZ13_diag ** m)
                            )
                            if np.allclose(result_diag.imag, 0):
                                diagonal_group.append(result_diag.real)

    return np.array(diagonal_group)


def four_qubit_diagonal_group() -> NDArray[np.float64]:
    """Generate the 4-qubit real diagonal Clifford group.

    Generated by products of P gates on each qubit and CZ gates on all 6 pairs,
    retaining elements with real diagonals. This yields 1024 elements.

    Returns:
        Array of shape (1024, 16) where each row is a diagonal group element.
    """
    n_qubits = 4

    P_gates = [create_pauli_z_diagonal(qubit, n_qubits) for qubit in range(1, n_qubits + 1)]

    pairs = [(1, 2), (2, 3), (3, 4), (1, 3), (1, 4), (2, 4)]
    cz_gates = [create_cz_diagonal(q1, q2, n_qubits) for q1, q2 in pairs]

    diagonal_group = []
    for i in range(1, 5):
        for j in range(1, 5):
            for k in range(1, 5):
                for l in range(1, 5):
                    for m in range(1, 3):
                        for n in range(1, 3):
                            for o in range(1, 3):
                                for p in range(1, 3):
                                    for q in range(1, 3):
                                        for r in range(1, 3):
                                            result_diag = (
                                                (P_gates[0] ** i)
                                                * (P_gates[1] ** j)
                                                * (P_gates[2] ** k)
                                                * (P_gates[3] ** l)
                                                * (cz_gates[0] ** m)
                                                * (cz_gates[1] ** n)
                                                * (cz_gates[2] ** o)
                                                * (cz_gates[3] ** p)
                                                * (cz_gates[4] ** q)
                                                * (cz_gates[5] ** r)
                                            )
                                            if np.allclose(result_diag.imag, 0):
                                                diagonal_group.append(result_diag.real)

    return np.array(diagonal_group)


def five_qubit_diagonal_group() -> NDArray[np.float64]:
    """Generate the 5-qubit real diagonal Clifford group.

    Generated by products of P gates on each qubit and CZ gates on all 10 pairs,
    retaining elements with real diagonals. This yields 32768 elements.

    Returns:
        Array of shape (32768, 32) where each row is a diagonal group element.
    """
    n_qubits = 5

    P_gates = [create_pauli_z_diagonal(qubit, n_qubits) for qubit in range(1, n_qubits + 1)]

    cz_gates = [
        create_cz_diagonal(i, j, n_qubits)
        for i in range(1, n_qubits + 1)
        for j in range(i + 1, n_qubits + 1)
    ]

    diagonal_group = []
    for i in range(1, 5):
        for j in range(1, 5):
            for k in range(1, 5):
                for l in range(1, 5):
                    for m in range(1, 5):
                        for cz_powers in np.ndindex(*([2] * 10)):  # 10 CZ pairs
                            result_diag = (
                                (P_gates[0] ** i)
                                * (P_gates[1] ** j)
                                * (P_gates[2] ** k)
                                * (P_gates[3] ** l)
                                * (P_gates[4] ** m)
                            )
                            for idx, power in enumerate(cz_powers):
                                result_diag *= cz_gates[idx] ** (power + 1)

                            if np.allclose(result_diag.imag, 0):
                                diagonal_group.append(result_diag.real)

    return np.array(diagonal_group)


def six_qubit_diagonal_group() -> NDArray[np.float64]:
    """Generate the 6-qubit real diagonal Clifford group.

    Generated by products of P gates on each qubit and CZ gates on all 15 pairs,
    retaining elements with real diagonals. This yields 2097152 elements.

    Note:
        This function is memory- and time-intensive. Expect several hours of
        runtime and multiple gigabytes of RAM for the full enumeration.

    Returns:
        Array of shape (2097152, 64) where each row is a diagonal group element.
    """
    n_qubits = 6

    P_gates = [create_pauli_z_diagonal(qubit, n_qubits) for qubit in range(1, n_qubits + 1)]

    cz_gates = [
        create_cz_diagonal(i, j, n_qubits)
        for i in range(1, n_qubits + 1)
        for j in range(i + 1, n_qubits + 1)
    ]

    diagonal_group = []
    for i in range(1, 5):
        for j in range(1, 5):
            for k in range(1, 5):
                for l in range(1, 5):
                    for m in range(1, 5):
                        for n in range(1, 5):
                            for cz_powers in np.ndindex(*([2] * 15)):  # 15 CZ pairs
                                result_diag = (
                                    (P_gates[0] ** i)
                                    * (P_gates[1] ** j)
                                    * (P_gates[2] ** k)
                                    * (P_gates[3] ** l)
                                    * (P_gates[4] ** m)
                                    * (P_gates[5] ** n)
                                )
                                for idx, power in enumerate(cz_powers):
                                    result_diag *= cz_gates[idx] ** (power + 1)

                                if np.allclose(result_diag.imag, 0):
                                    diagonal_group.append(result_diag.real)

    return np.array(diagonal_group)


if __name__ == '__main__':
    # Example: regenerate the 6-qubit dataset.
    # Edit the function call and output path for other qubit counts (1–5).
    # Warning: 6-qubit generation is slow and memory-intensive.
    group6 = six_qubit_diagonal_group()
    np.savetxt('datasets/real_diagonals/six_qubit_real_diagonal_clifford_groups.txt', group6)
    print("Number of 6-qubit Clifford elements:", group6.shape[0])
